---
- name: "Create directories on *NIX"
  when: ansible_os_family != 'Windows'
  block:
    - name: Configuration and data directories
      file:
        dest: "{{ dir_item }}"
        state: directory
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0700
      loop:
        - "{{ consul_config_path }}"
        - "{{ consul_configd_path }}"
        - "{{ consul_data_path }}"
      loop_control:
        loop_var: dir_item

    - name: Create run directory
      file:
        dest: "{{ consul_run_path }}"
        state: directory
        owner: "{{ consul_user }}"
        group: "{{ consul_group }}"
        mode: 0750
      when: not (consul_install_from_repo)

    - name: Create log directory
      file:
        dest: "{{ consul_log_path }}"
        state: directory
        owner: "{{ syslog_user if (consul_syslog_enable) or (consul_configure_syslogd) else consul_user }}"
        group: "{{ syslog_group if (consul_syslog_enable) or (consul_configure_syslogd) else consul_group }}"
        mode: 0700

    - name: Verify binary path
      file:
        path: "{{ consul_bin_path }}"
        state: directory
        owner: root
        mode: 0755
      when:
        # On macOS, we should not alter consul_bin_path, since it may be owned by the homebrew
        # user. This may cause the role to fail on macOS systems where homebrew is not
        # present, but in that case, the user should create the directory from their playbook
        # before running this role.
        - ansible_os_family != 'Darwin'
        - not (consul_install_from_repo)

- name: Create directories on Windows
  win_file:
    dest: "{{ dir_item }}"
    state: directory
  loop:
    - "{{ consul_config_path }}"
    - "{{ consul_configd_path }}"
    - "{{ consul_data_path }}"
    - "{{ consul_log_path }}"
    - "{{ consul_bin_path }}"
  loop_control:
    loop_var: dir_item
  when: ansible_os_family == 'Windows'
