---
- name: Prepare
  hosts: localhost
  connection: local

  tasks:
    - name: Prepare CI environment
      when: (lookup('env', 'CI'))
      block:
        - name: Install OS packages on controlling host
          when: ansible_distribution != 'MacOSX'
          package:
            name:
              - unzip
              - rsync
          become: true

        - name: Install netaddr dependency on controlling host
          pip:
            name: netaddr
            become: false

- name: Prepare host
  hosts: all

  tasks:
    - name: Install prerequisites
      package:
        name:
          - rsync
        state: present
