---
platforms:
  - name: debian-8
    groups:
      - consul_instances
    image: dokken/debian-8
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice

provisioner:
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python2.7
