---
- name: Restart consul
  import_tasks: restart_consul.yml
  listen: "restart consul"

- name: Start consul
  import_tasks: start_consul.yml
  listen: "start consul"

- name: Reload consul configuration
  import_tasks: reload_consul_conf.yml
  listen: "reload consul configuration"

- name: Restart dnsmasq
  service:
    name: dnsmasq
    enabled: true
    state: restarted
  become: true
  listen: "restart dnsmasq"

- name: Restart rsyslog
  import_tasks: restart_rsyslog.yml
  listen: "restart rsyslog"

- name: Restart syslog-ng
  import_tasks: restart_syslogng.yml
  listen: "restart syslog-ng"

- name: Restart syslog-ng
  import_tasks: restart_syslogng.yml
  listen: "restart syslog-ng"

- name: Start snapshot
  import_tasks: start_snapshot.yml
  listen: "start snapshot"

- name: Systemctl daemon-reload
  systemd:
    daemon_reload: true
  become: true
  listen: "systemctl daemon-reload"
