---
platforms:
  - name: fedora-31
    groups:
      - consul_instances
    image: dokken/fedora-31
    dockerfile: ../Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
