---
platforms:
  - name: centos-7
    groups:
      - consul_instances
    image: dokken/centos-7
    command: /usr/lib/systemd/systemd
    dockerfile: Dockerfile.j2
    privileged: true
    cgroup_parent: docker.slice
