---
platforms:
  - name: centos-7
    groups:
      - consul_instances
    image: dokken/centos-7
    dockerfile: ../Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
