---
dependency:
  name: shell
  command: "pip install git+https://github.com/ansible-community/molecule-docker.git@main"
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: timer,profile_tasks
      fact_caching: jsonfile
      fact_caching_connection: ./cache
      forks: 100
    connection:
      pipelining: True
  playbooks:
    prepare: ../prepare.yml
    converge: ../converge.yml
  inventory:
    group_vars:
      consul_instances:
        consul_node_role: bootstrap
verifier:
  name: testinfra
  directory: ../_tests
